### PR TITLE
Return all include dirs as absolute paths

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by michalmuskala** [comment]
Hi @filmor, thank you for the contribution.
Could you explain a bit more what problem is this change solving?

**Comment by ilya-klyuchnikov** [comment]
@filmor  - can you share step-by-step instructions to reproduce the behaviour? thanks

**Comment by filmor** [comment]
I'll try to reproduce the issue, but so far I've only seen the issue on our main codebase. The two submitted patches fix things for me, though.

**Comment by ilya-klyuchnikov** [comment]
`eqwalizer_rebar3` is not here anymore. The logic moved to ELP (https://github.com/WhatsApp/erlang-language-platform)

**Pull request closed without merging**
